### ISSUE TITLE
ERROR: Couldn't convert Next.js app to PWA.

### ISSUE THREAD

**Issue by KoCoder** [msaaddev/create-next-pwa#23]
![image](https://user-images.githubusercontent.com/83128842/123507495-08f3b980-d66a-11eb-885e-43b782615175.png)

I'm using your npm package ( installed global ) and tried to create an pwa ( with and without tailwind ) in vscode ( Terminal ), PS Admin and normal Powershell.

**Comment by msaaddev** [comment]
That's strange. When I tested it on Windows 10, it was working perfectly. Anyways, I will look into it and fix it in the next release. Thanks for pointing this out!

**Comment by msaaddev** [comment]
@KoCoder kindly try it again. I have published a release. Since you have installed the CLI globally, make sure you first update it by running `npm install -g create-next-pwa@latest`. Once you do this, run the CLI in either Powershell or CMD.

**Comment by KoCoder** [comment]
YES! Now it's working. Thank you for the work you put into it, I think it's great tool and am looking forward to using it for personal PWAs. Thanks again
